### PR TITLE
add all-contributors

### PR DESCRIPTION
**Pull request by askuy**

### CODE REVIEW

**Comment by ipfans** [comment]
@allcontributors add @askuy

**Comment by ipfans** [comment]
@allcontributors add @askuy for code

**Comment by ipfans** [comment]
@allcontributors add @astaxie for code

**Comment by ipfans** [comment]
@allcontributors add @songjiayang for code

**Comment by ipfans** [comment]
@allcontributors add @ryannvm for code

**Comment by ipfans** [comment]
@allcontributors add @qtsunami for code

**Comment by ipfans** [comment]
@allcontributors add @goxuetang for code

**Comment by ipfans** [comment]
@allcontributors add @CongLinNiao for code

**Comment by sijing233** [comment]
@ipfans

**Pull request merged**
